apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AlexKuznetsov7878/cloud_final.git
    targetRevision: main
    path: helm/flask
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true